ViewModels/ErreurViewModel.cs
namespace CoolGames.ViewModels
{
    public class ErreurViewModel
    {
        public int CodeErreur { get; set; }
        public string Message { get; set; }
    }
}

Controllers/ConsoleController.cs
using CoolGames.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CoolGames.Controllers
{
    public class ConsoleController : Controller
    {
        private readonly IConsoleRepository _consoleRepository;

        public ConsoleController(IConsoleRepository consoleRepository)
        {
            _consoleRepository = consoleRepository;
        }
        /// <summary>
        /// Permet d'afficher la liste de la console et les jeux associé
        /// </summary>
        /// <returns></returns>
        public ViewResult ListePs5()
        {
            return View(_consoleRepository.ListeConsolesPs5);
        }
        /// <summary>
        /// Permet d'afficher la liste de la console et les jeux associé
        /// </summary>
        /// <returns></returns>
        public ViewResult ListeXbox()
        {
            return View(_consoleRepository.ListeConsolesXbox);
        }
        /// <summary>
        /// Permet d'afficher la liste de la console et les jeux associé
        /// </summary>
        /// <returns></returns>
        public ViewResult ListeSwitch()
        {
            return View(_consoleRepository.ListeConsolesSwitch);
        }
        /// <summary>
        /// Permet d'afficher la page d'une console à modifier
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public ViewResult Modifier(int id)
        {
            ConsoleJeu console = _consoleRepository.GetConsole(id);
            return View(console);
        }
        /// <summary>
        /// Permet de modifier la console dépendament du nom de la console
        /// </summary>
        /// <param name="console"></param>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Modifier(ConsoleJeu console)
        {
            if (ModelState.IsValid)
            {
                if (console.Nom == "PlayStation 5")
                {
                    return RedirectToAction(nameof(ListePs5),new { id = console.Id });
                }
                else if (console.Nom == "Xbox Series X")
                {
                    return RedirectToAction(nameof(ListeXbox), new { id = console.Id });
                }
                else if (console.Nom == "Nintendo Switch")
                {
                    return RedirectToAction(nameof(ListeSwitch), new { id = console.Id });
                }
            }

            return View();
        }
    }
}

Controllers/ErreurController.cs
using CoolGames.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace CoolGames.Controllers
{
    public class ErreurController : Controller
    {
        /// <summary>
        /// Méthode pour gérer l'erreur 404
        /// </summary>
        /// <param name="code"></param>
        /// <returns></returns>
        [Route("Erreurs/Statut{code}")]
        public ViewResult GererErreur(int code)
        {
            ErreurViewModel erreurViewModel = new ErreurViewModel
            {
                CodeErreur = code,
            };

            if(code == 404)
            {
                erreurViewModel.Message = "Nous sommes vraiment désolée, mais cette page n'existe pas :(";
            }

            return View("Erreur",erreurViewModel);
        }
        /// <summary>
        /// Méthode pour gérer les autre Erreur(500 par exemple)
        /// </summary>
        /// <returns></returns>
        [Route("/ErreurGlobale")]
        public ViewResult ErreurGlobale()
        {
            ErreurViewModel erreurViewModel = new ErreurViewModel 
            {
                CodeErreur = HttpContext.Response.StatusCode,
                Message = "Oopsie, Une erreur s'est produite durant l'exécution de votre requête!"
            };

            return View("Erreur", erreurViewModel);
        }
    }
}

Controllers/JeuController.cs
using CoolGames.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using X.PagedList;

namespace CoolGames.Controllers
{
    public class JeuController : Controller
    {
        private readonly IJeuRepository _jeuRepository;


        public JeuController(IJeuRepository jeuRepository)
        {
            _jeuRepository = jeuRepository;
        }
        /// <summary>
        /// Méthode pour afficher la liste des jeux. De plus, il est possible de faire une recherche et changer de page
        /// </summary>
        /// <param name="recherche"></param>
        /// <param name="page"></param>
        /// <returns></returns>
        public ActionResult Liste(string recherche, int? page)
        {
            ViewBag.recherche = recherche;
            if (recherche == null)
            {
                var listeJeux = _jeuRepository.ListeJeux;
                int taillePage = 9;
                int numeroPage = (page ?? 1);
                return View(listeJeux.ToPagedList(numeroPage, taillePage));
            }
            else
            {
                var jeuxRecherches = _jeuRepository.Recherche(recherche);
                int taillePage = 9;
                int numeroPage = page ?? 1;
                var listeJeuxPaginee = jeuxRecherches.ToPagedList(numeroPage, taillePage);
                return View(listeJeuxPaginee);
            }
        }
        /// <summary>
        /// Voir les détails d'un jeu
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ViewResult Details(int id)
        {
            Jeu jeu = _jeuRepository.GetJeu(id);
            return View(jeu);


        }
        /// <summary>
        /// Supprimer un jeu. Seulement un admin peut le faire
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        public RedirectToActionResult Supprimer(int id)
        {
            _jeuRepository.SupprimerJeu(id);
            return RedirectToAction("Liste", _jeuRepository);
        }
        /// <summary>
        /// Afficher la page de modification d'un jeu. Seulement un admin peut le faire
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public ViewResult Modifier(int id)
        {
            Jeu jeu = _jeuRepository.GetJeu(id);
            return View(jeu);
        }
        /// <summary>
        /// Permet de modifier un jeu. Il y a aussi un ajout avec le téléversement d'image. Seulement un admin peut le faire
        /// </summary>
        /// <param name="jeu"></param>
        /// <param name="imageFile"></param>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Modifier(Jeu jeu, IFormFile imageFile)
        {
            if (ModelState.IsValid)
            {
                if (imageFile != null && imageFile.Length > 0)
                {
                    using (var memoryStream = new MemoryStream())
                    {
                        imageFile.CopyTo(memoryStream);
                        jeu.ImageData = memoryStream.ToArray();
                    }

                }
                _jeuRepository.ModifierJeu(jeu);
                return RedirectToAction(nameof(Liste), new { id = jeu.Id });
            }
            else
            {
                return View();
            }
        }
        /// <summary>
        /// Afficher la création d'un jeu
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public ViewResult Ajouter()
        {
            return View();
        }
        /// <summary>
        /// Creer le jeu. Seulement un admin peut le faire
        /// </summary>
        /// <param name="jeu"></param>
        /// <param name="imageFile"></param>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Ajouter(Jeu jeu, IFormFile imageFile)
        {
            if (ModelState.IsValid)
            {
                if (imageFile != null && imageFile.Length > 0)
                {
                    using (var memoryStream = new MemoryStream())
                    {
                        imageFile.CopyTo(memoryStream);
                        jeu.ImageData = memoryStream.ToArray();
                    }

                }
                _jeuRepository.AjouterJeu(jeu);
                return RedirectToAction(nameof(Liste));
            }
            else
            {
                return View();

            }
        }
        /// <summary>
        /// Permet de ne pas laisser mettre la même quantité 
        /// </summary>
        /// <param name="quantite"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult ValiderResultat(int quantite)
        {
            var resultat = _jeuRepository.ListeJeux.Any(j => j.Quantite == quantite);

            if (resultat)
            {
                return Json($"La quantité {quantite} existe déjà");
            }
            else
            {
                return Json(true);
            }
        }
    }
}

Controllers/RolesController.cs
using CoolGames.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CoolGames.Controllers
{
    /// <summary>
    /// Méthodes générales qui permet de créer un role et d'assigner un utilisateur au role
    /// </summary>
    public class RolesController : Controller
    {
        private RoleManager<IdentityRole> _roleManager;
        private UserManager<IdentityUser> _userManager;

        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<IdentityUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        [Authorize(Roles = "Admin")]
        public ViewResult Index()
        {
            return View(_roleManager.Roles);
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Creer()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Creer(string nom)
        {
            IdentityRole role = await _roleManager.FindByNameAsync(nom);

            if (role != null)
            {
                ModelState.AddModelError(nom, "Ce nom de rôle existe déjà, veuillez choisir un autre.");
                return View(nameof(Creer), nom);
            }

            if (ModelState.IsValid)
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(nom));

                if (result.Succeeded)
                    return RedirectToAction("Index");
                else
                {
                    foreach (IdentityError error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }
            }

            return View(nameof(Creer), nom);
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Supprimer(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);

            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);

                if (result.Succeeded)
                    return RedirectToAction("Index");
                else
                {
                    foreach (IdentityError error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }
            }

            return View("Index", _roleManager.Roles);
        }
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> ModifierRoleUsager(string roleId)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(roleId);

            IList<IdentityUser> membres = new List<IdentityUser>();
            List<IdentityUser> nonMembres = new List<IdentityUser>();

            List<IdentityUser> listeUsagers = _userManager.Users.ToList();

            membres = await _userManager.GetUsersInRoleAsync(role.Name);
            nonMembres = _userManager.Users.Where(user => !membres.Contains(user)).ToList();

            RoleMembresViewModel membresRoleVM = new RoleMembresViewModel
            {
                Role = role.Name,
                RoleId = role.Id,
                NonMembres = nonMembres,
                Membres = membres
            };

            return View(membresRoleVM);
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> ModifierRoleUsager(RoleMembresViewModel model)
        {
            IdentityResult results;
            if (!ModelState.IsValid)
            {
                foreach (string userId in model.AddUsers ?? new string[] { })
                {
                    IdentityUser user = await _userManager.FindByIdAsync(userId);
                    if (user != null)
                    {
                        results = await _userManager.AddToRoleAsync(user, model.Role);
                        if (!results.Succeeded)
                        {
                            foreach (IdentityError error in results.Errors)
                            {
                                ModelState.AddModelError("", error.Description);
                            }
                        }
                    }
                }

                foreach (string userId in model.RemoveUsers ?? new string[] { })
                {
                    IdentityUser user = await _userManager.FindByIdAsync(userId);
                    if (user != null)
                    {
                        results = await _userManager.RemoveFromRoleAsync(user, model.Role);
                        if (!results.Succeeded)
                        {
                            foreach (IdentityError error in results.Errors)
                            {
                                ModelState.AddModelError("", error.Description);
                            }
                        }
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            return View("ModifierRoleUsager", new RoleMembresViewModel { RoleId = model.RoleId });
        }


    }
}

ViewComponents/CompteurPanierViewComponent.cs
using CoolGames.Models;
using Microsoft.AspNetCore.Mvc;

namespace CoolGames.ViewComponents
{
    public class CompteurPanierViewComponent : ViewComponent
    {
        private readonly IPanierRepository _panier;

        public CompteurPanierViewComponent(IPanierRepository panier)
        {
            _panier = panier;
        }
        /// <summary>
        /// Permet d'aller chercher le nombre d'article pour l'afficher dans la vue et dans la session courante
        /// </summary>
        /// <returns></returns>
        public IViewComponentResult Invoke()
        {
            string _panierSessionId = HttpContext.Session.GetString("PanierSessionId");
            int nbJeuxPanier = _panier.NombreArticlesPanier(_panierSessionId);
            return View(nbJeuxPanier);
        }
    }
}

Views/Shared/Erreur.cshtml
@model ErreurViewModel
@{
    ViewData["Title"] = "Page d'erreur";
}

<h1>Oops!</h1>


<div class="alert alert-danger">
    <h1>Erreur @Model.CodeErreur</h1>
    <p>@Model.Message</p>
    <h6><a asp-controller="Home" asp-action="Index" class="btn btn-danger">Retourner à la page d'accueil</a></h6>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoolGames</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CoolGames.styles.css" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="/images/Logo.png" alt="" width="30" height="24" class="d-inline-block align-text-top" />
                    CoolGames
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Jeu" asp-action="Liste">Jeux</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Console</a>
                            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                                <li><a class="dropdown-item" asp-controller="Console" asp-action="ListePs5">Playstation 5</a></li>
                                <li><a class="dropdown-item" asp-controller="Console" asp-action="ListeXbox">Xbox Series X</a></li>
                                <li><a class="dropdown-item" asp-controller="Console" asp-action="ListeSwitch">Nintendo Switch</a></li>
                            </ul>
                        </li>                        
                        <li class="nav-item">
                            <partial name="_LoginPartial"/>
                        </li>
                        @if (ViewContext.HttpContext.User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-action="Index" asp-controller="Roles">Rôle</a>
                            </li>
                        }
                        
                        <li class="nav-item">
                            @await Component.InvokeAsync("CompteurPanier")
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CoolGames - <a class="btn-danger" asp-area="" asp-controller="Home" asp-action="Apropos">À propos de Abton</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("JQueryValidationScripts", required: false)
    @RenderSection("Scripts", required:false)
</body>
</html>